apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::953194687244:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NFSZ0N2QR43
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::953194687244:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-16T03:24:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1282"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2d2b23d8-0f98-4c97-9b28-f2ee92995fc7
