apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::953194687244:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-E9CKSLVJ1SDM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::953194687244:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-15T04:02:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1196"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f508052a-3c54-4402-ad96-b80f3b72a42b
